FROM python:3.12-slim

WORKDIR /app

COPY bot/requirements.txt /app/bot/requirements.txt
RUN pip install --no-cache-dir -r /app/bot/requirements.txt

COPY bot /app/bot

EXPOSE 8081

CMD ["python", "-m", "bot.main"]
